package pojo;
// Generated 15-feb-2016 11:57:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private String nif;
     private String nombre;
     private String domicilio;
     private Set direccions = new HashSet(0);

    public Persona() {
    }

	
    public Persona(String nif, String nombre, String domicilio) {
        this.nif = nif;
        this.nombre = nombre;
        this.domicilio = domicilio;
    }
    public Persona(String nif, String nombre, String domicilio, Set direccions) {
       this.nif = nif;
       this.nombre = nombre;
       this.domicilio = domicilio;
       this.direccions = direccions;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public Set getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set direccions) {
        this.direccions = direccions;
    }




}


